import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import * as React from 'react';
import {
	Box,
	Button,
	Container,
	Heading,
	Stack,
	Text,
	useBreakpointValue,
	Flex,
	Spacer,
	Grid,
	GridItem,
} from '@chakra-ui/react';
import Menu from '../components/Menu';

import About from '../components/Sections/About';
import Sidebar from '../components/Sidebar';
import Footer from '../components/Footer';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Flex h={{ lg: '100vh' }}>
				<Box position='sticky'>
					<Menu />
				</Box>
				<Box flex='1' as='main' overflowY='auto'>
					<Flex>
						<Box flexGrow='2'>
							<About />
							<About />
							<About />
							<About />
							<About />
							<About />
							{/* <Footer /> */}
						</Box>
						<Box flexGrow='1'>
							<Sidebar />
						</Box>
					</Flex>
				</Box>
			</Flex>
		</>
	);
};

export default Home;
